### PR TITLE
Update porch dependencies to nephio porch modules

### PR DESCRIPTION
**Pull request by efiacor**
#779 

Main change here was to remove the use of the replace directive for porch in the go.mod files.
Update the import paths.
Minor code updates.
Update the other dependencies to satisfy the existing codebase.

### CODE REVIEW

**Comment by radoslawc** [comment]
/override presubmit-nephio-lichen  
this is false positive and needs further investigation

**Comment by kispaljr** [comment]
changes look good and unit tests are all green on my machine

/lgtm

**Comment by henderiw** [comment]
I could not test but overall
/lgtm

**Pull request merged**
