### PR TITLE
Improvements for krm-functions/lib/test

### PR DESCRIPTION
**Pull request by kispaljr**
Add a slightly modified version of upstream testhelpers.RunGoldenTests(), that automatically creates the _actual_output.yaml.
More user-friendly error messages in case of failed failure-cases.

### CODE REVIEW

**Comment by henderiw** [comment]
does this impact all functions?

**Comment by henderiw** [comment]
some conflicts to be resolved.

**Comment by kispaljr** [comment]
> does this impact all functions?

no, this a backward compatible change, only adds new functionality

**Comment by kispaljr** [comment]
> some conflicts to be resolved.

done

**Review by gvbalaji — APPROVED** [review]
/lgtm

**Pull request merged**
