### PR TITLE
Import specializers and update go.mod

### PR DESCRIPTION
**Pull request by johnbelamaric**

### CODE REVIEW

**Comment by johnbelamaric** [comment]
@henderiw @ssharmasandeep 

I build nephio-controller-manager and pushed it to our docker hub, but it doesn't run. Well, it runs, but it says there are no reconcilers. I see that while they were committed, they are never loaded so they never register.

This PR fixes that - but it doesn't compile:

```
[hi on] jbelamaric@jbelamaric:~/proj/gh/nephio-project/nephio/operators/nephio-controller-manager$ make
go test ./... -v -coverprofile lcov.info 
# github.com/nephio-project/nephio/controllers/pkg/reconcilers/token
../../../../../../go/pkg/mod/github.com/nephio-project/nephio/controllers/pkg@v0.0.0-20230524181600-53f90020dbb6/reconcilers/token/reconciler.go:168:4: unknown field Scopes in struct literal of type gitea.CreateAccessTokenOption
../../../../../../go/pkg/mod/github.com/nephio-project/nephio/controllers/pkg@v0.0.0-20230524181600-53f90020dbb6/reconcilers/token/reconciler.go:168:20: undefined: gitea.AccessTokenScope
../../../../../../go/pkg/mod/github.com/nephio-project/nephio/controllers/pkg@v0.0.0-20230524181600-53f90020dbb6/reconcilers/token/reconciler.go:169:11: undefined: gitea.AccessTokenScopeRepo
FAIL
make: *** [../../default-go-test.mk:31: test] Error 1
[hi on] jbelamaric@jbelamaric:~/proj/gh/nephio-project/nephio/operators/nephio-controller-manager$ 

```

**Comment by johnbelamaric** [comment]
I commented out the token reconciler and now it's building successfully. I pushed that to the docker hub. But I do need the token reconciler :)

**Comment by ssharmasandeep** [comment]
@johnbelamaric let me look into it.

**Comment by johnbelamaric** [comment]
Fixed! Not sure if it's a "good" fix. PTAL

**Comment by johnbelamaric** [comment]
Docker build doesn't like my fix...working on it.

**Comment by johnbelamaric** [comment]
Ok. It seems to be working now. I guess I didn't do the right `go mod tidy` before?

**Comment by henderiw** [comment]
also we need to set the ENABLE flag in the env variable of the controller. Not sure if this is done

**Comment by ssharmasandeep** [comment]
The build has failed again .. I can fix this and create a PR after testing the Enable flag.

**Comment by johnbelamaric** [comment]
Fixed! The issue wasn't the ENABLE. The issue was that unless you import the module, the init code doesn't run. So, the reconcilers never actually registered. There were also a few little glitches (see commits).

**Comment by johnbelamaric** [comment]
```
ubuntu@nephio-r1-e2e:~$ k -n nephio-system logs nephio-controller-696bb46665-rb28w
Defaulted container "kube-rbac-proxy" out of: kube-rbac-proxy, controller
I0527 06:24:52.737216       1 main.go:190] Valid token audiences: 
I0527 06:24:52.737454       1 main.go:262] Generating self signed cert as no cert is provided
I0527 06:24:53.333469       1 main.go:311] Starting TCP socket on 0.0.0.0:8443
I0527 06:24:53.334074       1 main.go:318] Listening securely on 0.0.0.0:8443
ubuntu@nephio-r1-e2e:~$ k -n nephio-system logs nephio-controller-696bb46665-rb28w -c controller
I0527 06:24:54.729957       1 listener.go:44] controller-runtime/metrics "msg"="Metrics server is starting to listen" "addr"="127.0.0.1:8080"
I0527 06:24:54.730868       1 main.go:124] enabled reconcilers: tokens,repositories
I0527 06:24:54.730894       1 main.go:135] starting manager
I0527 06:24:54.731375       1 controller.go:186]  "msg"="Starting EventSource" "controller"="TokenController" "controllerGroup"="infra.nephio.org" "controllerKind"="Token" "source"="kind source: *v1alpha1.Token"
I0527 06:24:54.731401       1 controller.go:194]  "msg"="Starting Controller" "controller"="TokenController" "controllerGroup"="infra.nephio.org" "controllerKind"="Token"
I0527 06:24:54.731395       1 internal.go:369]  "msg"="Starting server" "addr"={"IP":"127.0.0.1","Port":8080,"Zone":""} "kind"="metrics" "path"="/metrics"
I0527 06:24:54.731487       1 controller.go:186]  "msg"="Starting EventSource" "controller"="RepositoryController" "controllerGroup"="infra.nephio.org" "controllerKind"="Repository" "source"="kind source: *v1alpha1.Repository"
I0527 06:24:54.731521       1 controller.go:194]  "msg"="Starting Controller" "controller"="RepositoryController" "controllerGroup"="infra.nephio.org" "controllerKind"="Repository"
I0527 06:24:54.731604       1 internal.go:369]  "msg"="Starting server" "addr"={"IP":"::","Port":8081,"Zone":""} "kind"="health probe"
I0527 06:24:54.832054       1 controller.go:228]  "msg"="Starting workers" "controller"="RepositoryController" "controllerGroup"="infra.nephio.org" "controllerKind"="Repository" "worker count"=1
I0527 06:24:54.832090       1 controller.go:228]  "msg"="Starting workers" "controller"="TokenController" "controllerGroup"="infra.nephio.org" "controllerKind"="Token" "worker count"=1
ubuntu@nephio-r1-e2e:~$ ^C
ubuntu@nephio-r1-e2e:~$ 

```

**Comment by johnbelamaric** [comment]
Though I don't know why the ipam and vlan specializers didn't start

**Comment by ssharmasandeep** [comment]
Another heads-up, there could be more glitches in e2e functionality. The configuration that is getting passed currently is not complete. Parameters like IP address, giteaclient etc. are not passed from the controller. I had to test e2e after including all reconcilers.

**Comment by johnbelamaric** [comment]
Ok, so with this build it runs...but it crashes when it sees a repo because ControllerConfig gitea client is never set here: 

https://github.com/nephio-project/nephio/blob/main/operators/nephio-controller-manager/main.go#L107

So we end up with a crash here:

https://github.com/nephio-project/nephio/blob/main/controllers/pkg/reconcilers/repository/reconciler.go#L98

since `r.giteaClient` is nil.

**Comment by ssharmasandeep** [comment]
Yes, so I am working  on it and will raise the PR in some time with these fixes.

**Comment by johnbelamaric** [comment]
> Another heads-up, there could be more glitches in e2e functionality. The configuration that is getting passed currently is not complete. Parameters like IP address, giteaclient etc. are not passed from the controller. I had to test e2e after including all reconcilers.

Yep, that's what I am seeing.

Maybe we can merge this PR as it at least works "better"? Then debug those things separately?

**Comment by ssharmasandeep** [comment]
Since I have a similar change in my local, it will cause conflicts for me.  But it is ok, I will refresh the local branch after this merge.

**Comment by johnbelamaric** [comment]
/approve

Can you give me an LGTM?

**Pull request merged**
