### PR TITLE
De duplication logic to NF Deploy Fn Param Ref

### PR DESCRIPTION
**Pull request by aakashchan**
These changes will ensure we have nf deploy fn to apply de dupulication logic to NF Deploy Param Ref

1. Changes to Add Dependency to check if it already exist before adding. Thanks @gvbalaji for the code snippet in chat.
2. Added test cases to handle dependency, if same file is present multiple times. Its not in our use case, but its better to add that too.
3. Added changes to pipeline tests to ensure, if I run the NF Deploy Fn multiples after that, it doesn't break the idempotency principle.

Docker image I used for testing - [docker.io/lostbrain/nfdeployfn:test-5](http://docker.io/lostbrain/nfdeployfn:test-5)

### CODE REVIEW

**Review by gvbalaji — APPROVED** [review]
/approve

**Comment by arora-sagar** [comment]
I am just testing it.

**Comment by electrocucaracha** [comment]
It seems like the [Unit test is passing ](http://prow.nephio.io/view/gs/prow-nephio-sig-release/pr-logs/pull/nephio-project_nephio/494/presubmit-nephio-go-test/1752760937103757312#1:build-log.txt%3A1431). I'm okay with these changes, but I'll wait until  @arora-sagar ends his testing.

**Comment by arora-sagar** [comment]
Looks good not, no duplicates. We can merge I suppose. 


```
apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: # kpt-merge: smf-example/smf-example
  name: smf-core
  namespace: oai-core
  annotations:
    internal.kpt.dev/upstream-identifier: 'workload.nephio.org|NFDeployment|smf-example|smf-example'
spec:
  provider: smf.openairinterface.org
  parametersRefs:
  - name: oai-smf-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
  - name: smf-core-upf-edge
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config
  networkInstances:
  - name: vpc-internal
    interfaces:
    - n4
  interfaces:
  - name: n4
    ipv4:
      address: 172.1.0.254/24
      gateway: 172.1.0.1
    vlanID: 4
  capacity:
    maxDownlinkThroughput: "0"
    maxNFConnections: 5
    maxSessions: 500
    maxUplinkThroughput: "0"
```

**Review by s3wong — APPROVED** [review]

**Comment by gvbalaji** [comment]
thanks @aakashchan for the quick fix.

**Comment by radoslawc** [comment]
Reverting the change for testing new release img.

**Pull request merged**
