### PR TITLE
Pkg Specialization Pipeline tests

### PR DESCRIPTION
**Pull request by kispaljr**
Add a "middle-sized test" that can test a chain/pipeline of multiple KRM functions end-to-end, but doesn't need a Kubernetes cluster, because it is built on the built-in Go testing framework.
This is less than a real integration or end-to-end test, but more than a unit test, even more than the component tests of single KRM function.

Fixes https://github.com/nephio-project/nephio/issues/165

### CODE REVIEW

**Review by gvbalaji — COMMENTED** [review]
Thanks @kispaljr . Should dnn function be part of this PR?  I was thinking it may be in a different PR already.

**Review by aakashchan — APPROVED** [review]
lgtm

**Comment by gvbalaji** [comment]
Thanks @kispaljr . Looks like tests are failing for this PR. Can you PTAL?

**Pull request merged**
