### PR TITLE
sdk nil pointer. check missing

### PR DESCRIPTION
**Pull request by henderiw**
fixed a missing nil pointer ref check

### CODE REVIEW

**Review by gvbalaji — COMMENTED** [review]
Thanks @henderiw . Looks like this includes some other commits as well (getters for Kubeobject). Can you please check?

**Comment by henderiw** [comment]
@gvbalaji strange it came in as I was changing this from base, but reverted. Thx

**Review by ganchandrasekaran — APPROVED** [review]

**Pull request merged**
