### PR TITLE
De duplication logic to NF Deploy Fn Param Ref (#494)

### PR DESCRIPTION
**Pull request by aakashchan**
Solves #493 
These changes will ensure we have nf deploy fn to apply de dupulication logic to NF Deploy Param Ref

1. Changes to Add Dependency to check if it already exist before adding. Thanks @gvbalaji for the code snippet in chat.
2. Added test cases to handle dependency, if same file is present multiple times. Its not in our use case, but its better to add that too.
3. Added changes to pipeline tests to ensure, if I run the NF Deploy Fn multiples after that, it doesn't break the idempotency principle.

### CODE REVIEW

**Comment by efiacor** [comment]
Hi @aakashchan , is this change still relevant?

**Comment by tliron** [comment]
@aakashchan bump :)

**Comment by aakashchan** [comment]
@radoslawc I'm waiting for you confirm. In my testing environment, I didn't face issue and not able to replicate.

**Comment by efiacor** [comment]
Looks like this change is needed. Please review and progress.

**Pull request merged**
