### PR TITLE
Rename variable for code readability

### PR DESCRIPTION
**Pull request by subh007**
Renamed variable for code readability.
changed `cr` to `network`.

### CODE REVIEW

**Comment by henderiw** [comment]
I prefer not to do this change as you can easily copy paste in other controllers. otherwise you have to change the variables all the time whereas now we need to change it in the complete code all the time.

**Comment by subh007** [comment]
> I prefer not to do this change as you can easily copy paste in other controllers. otherwise you have to change the variables all the time whereas now we need to change it in the complete code all the time.

Hello @henderiw ,

I feel we should make code readable by providing context in variable name similar to other [reconcilers](https://github.com/nephio-project/nephio/blob/main/controllers/pkg/reconcilers/generic-specializer/reconciler.go#L100). I think while copying the code author should provide necessary context/changes.

**Comment by henderiw** [comment]
> > I prefer not to do this change as you can easily copy paste in other controllers. otherwise you have to change the variables all the time whereas now we need to change it in the complete code all the time.
> 
> Hello @henderiw ,
> 
> I feel we should make code readable by providing context in variable name similar to other [reconcilers](https://github.com/nephio-project/nephio/blob/main/controllers/pkg/reconcilers/generic-specializer/reconciler.go#L100). I think while copying the code author should provide necessary context/changes.

see if you write an SDK or a library the meaning of a variable depends on the context. If you write a reconcile for a KRM object, the context is that KRM object and you know the context. It is overkill to name everything a used as it goes against data driven programming

**Comment by subh007** [comment]
> > > I prefer not to do this change as you can easily copy paste in other controllers. otherwise you have to change the variables all the time whereas now we need to change it in the complete code all the time.
> > 
> > 
> > Hello @henderiw ,
> > I feel we should make code readable by providing context in variable name similar to other [reconcilers](https://github.com/nephio-project/nephio/blob/main/controllers/pkg/reconcilers/generic-specializer/reconciler.go#L100). I think while copying the code author should provide necessary context/changes.
> 
> see if you write an SDK or a library the meaning of a variable depends on the context. If you write a reconcile for a KRM object, the context is that KRM object and you know the context. It is overkill to name everything a used as it goes against data driven programming

Sure, I was trying to follow the convention used in `generic-specializer`, which I feel helps reader to understand the code.
Please let me know if I should abandon this change.

**Comment by efiacor** [comment]
> > > > I prefer not to do this change as you can easily copy paste in other controllers. otherwise you have to change the variables all the time whereas now we need to change it in the complete code all the time.
> > > 
> > > 
> > > Hello @henderiw ,
> > > I feel we should make code readable by providing context in variable name similar to other [reconcilers](https://github.com/nephio-project/nephio/blob/main/controllers/pkg/reconcilers/generic-specializer/reconciler.go#L100). I think while copying the code author should provide necessary context/changes.
> > 
> > 
> > see if you write an SDK or a library the meaning of a variable depends on the context. If you write a reconcile for a KRM object, the context is that KRM object and you know the context. It is overkill to name everything a used as it goes against data driven programming
> 
> Sure, I was trying to follow the convention used in `generic-specializer`, which I feel helps reader to understand the code. Please let me know if I should abandon this change.

I would agree that naming variables descriptively helps the reader. In this case, for me, naming the CR to align with it's relevant KRM helps the reader and makes the code flow better. Naming conventions for variables can be difficult to align on but imho using 2-3 letter acronymns reduces the readability of the code.

**Review by efiacor — APPROVED** [review]

**Comment by henderiw** [comment]
> > > > > I prefer not to do this change as you can easily copy paste in other controllers. otherwise you have to change the variables all the time whereas now we need to change it in the complete code all the time.
> > > > 
> > > > 
> > > > Hello @henderiw ,
> > > > I feel we should make code readable by providing context in variable name similar to other [reconcilers](https://github.com/nephio-project/nephio/blob/main/controllers/pkg/reconcilers/generic-specializer/reconciler.go#L100). I think while copying the code author should provide necessary context/changes.
> > > 
> > > 
> > > see if you write an SDK or a library the meaning of a variable depends on the context. If you write a reconcile for a KRM object, the context is that KRM object and you know the context. It is overkill to name everything a used as it goes against data driven programming
> > 
> > 
> > Sure, I was trying to follow the convention used in `generic-specializer`, which I feel helps reader to understand the code. Please let me know if I should abandon this change.
> 
> I would agree that naming variables descriptively helps the reader. In this case, for me, naming the CR to align with it's relevant KRM helps the reader and makes the code flow better. Naming conventions for variables can be difficult to align on but imho using 2-3 letter acronymns reduces the readability of the code.

go in general promotes short names if you read the coding guidelines.

**Comment by subh007** [comment]
> > > > > > I prefer not to do this change as you can easily copy paste in other controllers. otherwise you have to change the variables all the time whereas now we need to change it in the complete code all the time.
> > > > > 
> > > > > 
> > > > > Hello @henderiw ,
> > > > > I feel we should make code readable by providing context in variable name similar to other [reconcilers](https://github.com/nephio-project/nephio/blob/main/controllers/pkg/reconcilers/generic-specializer/reconciler.go#L100). I think while copying the code author should provide necessary context/changes.
> > > > 
> > > > 
> > > > see if you write an SDK or a library the meaning of a variable depends on the context. If you write a reconcile for a KRM object, the context is that KRM object and you know the context. It is overkill to name everything a used as it goes against data driven programming
> > > 
> > > 
> > > Sure, I was trying to follow the convention used in `generic-specializer`, which I feel helps reader to understand the code. Please let me know if I should abandon this change.
> > 
> > 
> > I would agree that naming variables descriptively helps the reader. In this case, for me, naming the CR to align with it's relevant KRM helps the reader and makes the code flow better. Naming conventions for variables can be difficult to align on but imho using 2-3 letter acronymns reduces the readability of the code.
> 
> go in general promotes short names if you read the coding guidelines.

@henderiw 
I observed that the many places we have used long names in our code. 
I also checked the [golang style guide](https://google.github.io/styleguide/go/decisions#variable-names) , I feel we should rename the variable for readability.

> The general rule of thumb is that the length of a name should be proportional to the size of its scope and inversely proportional to the number of times that it is used within that scope. A variable created at file scope may require multiple words, whereas a variable scoped to a single inner block may be a single word or even just a character or two, to keep the code clear and avoid extraneous information.

Please let me know your thoughts!

**Comment by efiacor** [comment]
Can we get a consensus on this @henderiw @johnbelamaric @tliron @s3wong @liamfallon @subh007 ?
I agree with the sentiment that making code more human readable is optimal.

**Comment by tliron** [comment]
I am in favor of this PR.

For what it's worth, I think the Go practice (common, but not universal) of promoting acronyms and short names is a terrible step backward.

**Comment by liamfallon** [comment]
I also agree
/approve

**Comment by efiacor** [comment]
Hi @subh007 , rebase required here. Thanks

**Comment by subh007** [comment]
Create a new pull request #487

**Comment by subh007** [comment]
@henderiw @liamfallon @tliron @efiacor , could we conclude this patch.

**Comment by tliron** [comment]
/lgtm

I think the blocker is @henderiw , we may need to discuss more.

**Pull request closed without merging**
