### PR TITLE
added code of conduct

### PR DESCRIPTION
**Pull request by VedRatan**
added CODE_OF_CONDUCT.md file to improve [LFInsights](https://insights.lfx.linuxfoundation.org/foundation/ena/overview?project=ena&bestPractice=false) score for Nephio.

### CODE REVIEW

**Comment by VedRatan** [comment]
Any updates on this one?

**Comment by liamfallon** [comment]
> Any updates on this one?

Hi @VedRatan , thanks very much for this PR and the other PRs you have raised. I'm not sure what the process is for accepting such PRs so I'll ask on the SIG-Automation slack channel.

**Comment by gvbalaji** [comment]
Is this the standard COC from LFN?

**Comment by VedRatan** [comment]
@gvbalaji here is the proposal for [LFN COC ](https://wiki.lfnetworking.org/download/attachments/15631555/2019_01_29_LFNCodeOfContactProposalV2.docx?version=1&modificationDate=1560896428000&api=v2)

**Comment by tliron** [comment]
Let's please bring up in the TSC meeting, unclear to me if the Nephio community has adopted this CoC or has to adopt this CoC.

**Comment by nyrahul** [comment]
> Let's please bring up in the TSC meeting, unclear to me if the Nephio community has adopted this CoC or has to adopt this CoC.

Just for the record, [this was discussed on Mar 14th TSC call](https://lists.nephio.org/g/sig-security/message/65) and the decision was to point to LFN COC as described in the thread.

**Pull request merged**
