### PR TITLE
added getters into kubeobject

### PR DESCRIPTION
**Pull request by henderiw**
added getters to kubeobject

### CODE REVIEW

**Review by johnbelamaric — COMMENTED** [review]
Do we think it's safe to ignore these errors? What could be the cause of these errors? Malformed YAML?

**Review by gvbalaji — COMMENTED** [review]
Thanks @henderiw .  Now that we refactored and just extending the base kubeobject, not sure we need these indirection methods as we can not ignore errors. Probably we can just invoke the base methods from the methods in the individual libraries ( interface, nad etc) ?

**Comment by henderiw** [comment]
we can expose the errors and present it to the user if needed.

**Comment by johnbelamaric** [comment]
But wouldn't that be the same as calling the original methods?

**Comment by johnbelamaric** [comment]
Oh, I see it would go from 3 to 2 return values?

**Comment by henderiw** [comment]
Right now this is an intermediate step  until we go to full go struct approach. We need to validate if the gostruct approach works in all circumstances.

**Pull request closed without merging**
