### PR TITLE
NFDeployment newKO

### PR DESCRIPTION
**Pull request by aakashchan**
aligned the interface with the new parser implementation
added setters using the real types as this eases validation.

Unit tested for UPFDeployment type. I will add more tests SMF and AMF type in subsequent PRs if needed.

### CODE REVIEW

**Review by gvbalaji — COMMENTED** [review]
Thanks @aakashchan . Looks good but I have a question. With the type safety provided at the base `KubeObjectExt` is this layer really needed? Can the functions directly call the base library with the required type safety?

**Comment by henderiw** [comment]
The differences between the approaches are very small.
Here is my breakdown:
- KubeObjectExt: expects the developer to know generics and add the right type in the generic field of the go struct. More error prune, but checked in the library.
- Explicit typed interface. needs explicit code although could be generated. Easier for people to grasp.

So it depends on the target for these. A deep go developer prefers KubeObjectExt, the less experienced dev prefers Explicit typed interfaces. How I personally look at this is I look at the consumer of this and given the SDK targets less experienced people. As such this is why we created the explicit methods.

Personally I prefer KubeObjectExt, but the barrier for the consumers is higher.
My 2 cents.

Example Here.

Explicit
			alloc, err := vlanlibv1alpha1.NewFromKubeObject(vlanalloc)
			if err != nil {
				return nil, err
			}
KubeObjectExt
			alloc, err := ko.NewFromKubeObject[*vlanv1alpha1.VLANAllocation](vlanalloc)
			if err != nil {
				return nil, err
			}
			
@aakashchan what is your view?

**Comment by aakashchan** [comment]
@henderiw @gvbalaji 

1. Currently, the nf deploy lib already expects user to know about this generic type. So we are not obliterating generics from user completely. I don't see the point of repeating the code in library without generics for all 3 three types.

```
type NfDeploymentType interface {
	*nephiodeployv1alpha1.UPFDeployment | *nephiodeployv1alpha1.SMFDeployment | *nephiodeployv1alpha1.AMFDeployment
}
```
2. Another draw back is, SetSpec() or SetStatus() expects argument of `NFDeploymentSpec` than  `UPFDeployment`. Here, library couldn't do much even with generics.

3. Bright side, It ensures tighter type safety on one hand. 

```
i, err := NewFromYAML[*nephiodeployv1alpha1.UPFDeployment]([]byte(tc.file))
g, err := i.GetGoStruct()
// error check ...
```

I also prefer using KubeObjExt directly over wrapper lib.

**Comment by henderiw** [comment]
if you do this we do not expose generics to the user.
// NewFromKubeObject creates a new parser interface
// It expects a *fn.KubeObject as input representing the serialized yaml file
func NewFromKubeObject(o *fn.KubeObject) (*Interface, error) {
	r, err := kubeobject.NewFromKubeObject[*nephioreqv1alpha1.Interface](o)
	if err != nil {
		return nil, err
	}
	return &Interface{*r}, nil
}

**Comment by henderiw** [comment]
Also Isti made the SetSpec and SetStatus such that they can also use the generic type. But this PR is not merged yet

**Comment by aakashchan** [comment]
Closing this as we decided to use Kubeobject ext directly

**Pull request closed without merging**
